import a from "../assets/bigletters/a.jpg"
import b from "../assets/bigletters/b.jpg"
import c from "../assets/bigletters/c.jpg"
import d from "../assets/bigletters/d.jpg"
import e from "../assets/bigletters/e.jpg"
import f from "../assets/bigletters/f.jpg"
import g from "../assets/bigletters/g.jpg"
import h from "../assets/bigletters/h.jpg"
import i from "../assets/bigletters/i.jpg"
import j from "../assets/bigletters/j.jpg"
import k from "../assets/bigletters/k.jpg"
import l from "../assets/bigletters/l.jpg"
import m from "../assets/bigletters/m.jpg"
import n from "../assets/bigletters/n.jpg"
import o from "../assets/bigletters/o.jpg"
import p from "../assets/bigletters/p.jpg"
import q from "../assets/bigletters/q.jpg"
import r from "../assets/bigletters/r.jpg"
import s from "../assets/bigletters/s.jpg"
import t from "../assets/bigletters/t.jpg"
import u from "../assets/bigletters/u.jpg"
import v from "../assets/bigletters/v.jpg"
import w from "../assets/bigletters/w.jpg"
import x from "../assets/bigletters/x.jpg"
import y from "../assets/bigletters/y.jpg"
import z from "../assets/bigletters/z.jpg"


export { a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z }
