import a from "../assets/pngletters/a.jpg"
import b from "../assets/pngletters/b.jpg"
import c from "../assets/pngletters/c.jpg"
import d from "../assets/pngletters/d.jpg"
import e from "../assets/pngletters/e.jpg"
import f from "../assets/pngletters/f.jpg"
import g from "../assets/pngletters/g.jpg"
import h from "../assets/pngletters/h.jpg"
import i from "../assets/pngletters/i.jpg"
import j from "../assets/pngletters/j.jpg"
import k from "../assets/pngletters/k.jpg"
import l from "../assets/pngletters/l.jpg"
import m from "../assets/pngletters/m.jpg"
import n from "../assets/pngletters/n.jpg"
import o from "../assets/pngletters/o.jpg"
import p from "../assets/pngletters/p.jpg"
import q from "../assets/pngletters/q.jpg"
import r from "../assets/pngletters/r.jpg"
import s from "../assets/pngletters/s.jpg"
import t from "../assets/pngletters/t.jpg"
import u from "../assets/pngletters/u.jpg"
import v from "../assets/pngletters/v.jpg"
import w from "../assets/pngletters/w.jpg"
import x from "../assets/pngletters/x.jpg"
import y from "../assets/pngletters/y.jpg"
import z from "../assets/pngletters/z.jpg"
import space from "../assets/alphabets/space.png"


export { a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, space }
